FROM python:3.9
LABEL maintainer="bekaryukovmv@gmail.com"

RUN mkdir /app && mkdir /app/TODO_project
WORKDIR /app/TODO_project

COPY ./Pipfile ./Pipfile.lock /app/TODO_project/
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install pipenv && pipenv install --ignore-pipfile --system --deploy

EXPOSE 8000
