FROM python:3.9
LABEL maintainer="bekaryukovmv@gmail.com"

RUN mkdir /app && mkdir /app/TODO_project
RUN mkdir /app/TODO_project/TODO_list/
RUN mkdir /app/TODO_project/TODO_list/static
WORKDIR /app/TODO_project

COPY ./Pipfile ./Pipfile.lock /app/TODO_project/
RUN echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install pipenv && pipenv install --ignore-pipfile --system --deploy

EXPOSE 8000
